development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3
  

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: yourmd
  host: aa1rywc9t8x5oxb.cv9qibmmu6yi.us-east-1.rds.amazonaws.com
  port: 3306

